const wardrobeData = {
  "lastUpdated": "2026-03-15",
  "source": "ACloset via Natalia",
  "items": [
    {"id": 1, "image": "part1_image0.jpeg", "brand": "ROBERT BARAKETT", "category": "long-sleeve-shirt", "color": "white", "style": ["casual"]},
    {"id": 2, "image": "part1_image1.jpeg", "brand": "ROBERT BARAKETT", "category": "polo", "color": "black", "style": ["smart-casual"]},
    {"id": 3, "image": "part1_image2.jpeg", "brand": "H&M", "category": "jeans", "color": "gray", "style": ["casual"]},
    {"id": 4, "image": "part1_image3.jpeg", "brand": "ZARA", "category": "jeans", "color": "gray", "style": ["casual"]},
    {"id": 5, "image": "part1_image4.jpeg", "brand": "REISS", "category": "jacket", "color": "beige", "style": ["streetwear", "casual"]},
    {"id": 6, "image": "part1_image5.jpeg", "brand": "ROBERT BARAKETT", "category": "t-shirt", "color": "burgundy", "style": ["casual"]},
    {"id": 7, "image": "part1_image6.jpeg", "brand": "BOSS", "category": "jacket", "color": "black", "style": ["formal", "smart-casual"]},
    {"id": 8, "image": "part1_image7.jpeg", "brand": "ZARA", "category": "coat", "color": "gray", "style": ["formal"]},
    {"id": 9, "image": "part1_image8.jpeg", "brand": "TOPMAN", "category": "jeans", "color": "black", "style": ["casual"]},
    {"id": 10, "image": "part1_image9.jpeg", "brand": "YOUNGLA", "category": "t-shirt", "color": "gray", "style": ["casual", "athletic"]},
    {"id": 11, "image": "part1_image10.jpeg", "brand": "YOUNGLA", "category": "t-shirt", "color": "black", "style": ["casual", "athletic"]},
    {"id": 12, "image": "part1_image11.jpeg", "brand": "WOLF & SHEPHERD", "category": "sneakers", "color": "white", "style": ["casual", "smart-casual"]},
    {"id": 13, "image": "part1_image12.jpeg", "brand": "ORO", "category": "boots", "color": "olive", "style": ["casual", "smart-casual"]},
    {"id": 14, "image": "part1_image13.jpeg", "brand": "UNDER ARMOUR", "category": "joggers", "color": "black", "style": ["athletic", "casual"]},
    {"id": 15, "image": "part1_image14.jpeg", "brand": "H&M", "category": "jacket", "color": "beige", "style": ["casual"]},
    {"id": 16, "image": "part1_image15.jpeg", "brand": "ZARA", "category": "shacket", "color": "light-blue", "style": ["casual"]},
    {"id": 17, "image": "part1_image16.jpeg", "brand": "WAX LONDON", "category": "shacket", "color": "beige", "style": ["casual"]},
    {"id": 18, "image": "part1_image17.jpeg", "brand": "TRAVIS MATHEW", "category": "pants", "color": "black", "style": ["smart-casual"]},
    {"id": 19, "image": "part1_image18.jpeg", "brand": "NIKE", "category": "sweatshirt", "color": "burgundy", "style": ["athletic", "collegiate"]},
    {"id": 20, "image": "part1_image19.jpeg", "brand": "ALLSAINTS", "category": "sweater", "color": "olive", "style": ["casual"]},
    {"id": 21, "image": "part1_image20.jpeg", "brand": "LEX DEUS", "category": "jacket", "color": "olive", "style": ["casual"]},
    {"id": 22, "image": "part1_image21.jpeg", "brand": "UNDER ARMOUR", "category": "quarter-zip", "color": "charcoal", "style": ["athletic"]},
    {"id": 23, "image": "part1_image22.jpeg", "brand": "YOUNGLA", "category": "polo", "color": "black", "style": ["smart-casual"]},
    {"id": 24, "image": "part1_image23.jpeg", "brand": "WOLF & SHEPHERD", "category": "sneakers", "color": "white", "style": ["casual", "smart-casual"]},
    {"id": 25, "image": "part1_image24.jpeg", "brand": "TRAVIS MATHEW", "category": "pants", "color": "navy", "style": ["smart-casual"]},
    {"id": 26, "image": "part1_image25.jpeg", "brand": "H&M", "category": "jacket", "color": "gray", "style": ["casual"]},
    {"id": 27, "image": "part1_image26.jpeg", "brand": "ZARA", "category": "shacket", "color": "white", "style": ["casual"]},
    {"id": 28, "image": "part1_image27.jpeg", "brand": "H&M", "category": "shirt", "color": "white", "style": ["casual", "smart-casual"]},
    {"id": 29, "image": "part1_image28.jpeg", "brand": "BOSS", "category": "sneakers", "color": "white", "style": ["casual"]},
    {"id": 30, "image": "part1_image29.jpeg", "brand": "PUBLIC REC", "category": "henley", "color": "black", "style": ["casual"]},
    {"id": 31, "image": "part1_image30.jpeg", "brand": "ROBERT BARAKETT", "category": "t-shirt", "color": "black", "style": ["casual"]},
    {"id": 32, "image": "part1_image31.jpeg", "brand": "ALLSAINTS", "category": "sweater", "color": "gray", "style": ["casual"]},
    {"id": 33, "image": "part1_image32.jpeg", "brand": "BOSS", "category": "quarter-zip", "color": "burgundy", "style": ["smart-casual"]},
    {"id": 34, "image": "part1_image33.jpeg", "brand": "RIVER ISLAND", "category": "coat", "color": "camel", "style": ["formal", "smart-casual"]},
    {"id": 35, "image": "part1_image34.jpeg", "brand": "RODD & GUNN", "category": "blazer", "color": "green", "style": ["smart-casual"]},
    {"id": 36, "image": "part1_image35.jpeg", "brand": "LUCKY BRAND", "category": "blazer", "color": "navy", "style": ["smart-casual", "formal"]},
    {"id": 37, "image": "part1_image36.jpeg", "brand": "KSUBI", "category": "jeans", "color": "black", "style": ["streetwear"]},
    {"id": 38, "image": "part1_image37.jpeg", "brand": "FRAME", "category": "chinos", "color": "beige", "style": ["casual", "smart-casual"]},
    {"id": 39, "image": "part1_image38.jpeg", "brand": "ZARA", "category": "jeans", "color": "gray", "style": ["streetwear"]},
    {"id": 40, "image": "part1_image39.jpeg", "brand": "ROBERT BARAKETT", "category": "t-shirt", "color": "white", "style": ["casual"]},
    {"id": 41, "image": "part1_image40.jpeg", "brand": "YOUNGLA", "category": "t-shirt", "color": "white", "style": ["casual", "athletic"]},
    {"id": 42, "image": "part1_image41.jpeg", "brand": "UNDER ARMOUR", "category": "long-sleeve-shirt", "color": "white", "style": ["athletic"]},
    {"id": 43, "image": "part1_image42.jpeg", "brand": null, "category": "hoodie", "color": "gray", "style": ["casual", "collegiate"]},
    {"id": 44, "image": "part1_image43.jpeg", "brand": null, "category": "hoodie", "color": "gray", "style": ["casual", "collegiate"]},
    {"id": 45, "image": "part1_image44.jpeg", "brand": "UNDER ARMOUR", "category": "hoodie", "color": "cream", "style": ["casual"]},
    {"id": 46, "image": "part1_image45.jpeg", "brand": "THEORY", "category": "shirt", "color": "black", "style": ["formal"]},
    {"id": 47, "image": "part1_image46.jpeg", "brand": "ZARA", "category": "sweater", "color": "black", "style": ["casual"]},
    {"id": 48, "image": "part1_image47.jpeg", "brand": "CLAIM DEFAME", "category": "jacket", "color": "navy", "style": ["casual", "streetwear"]},
    {"id": 49, "image": "part1_image48.jpeg", "brand": "ZARA", "category": "sweater", "color": "charcoal", "style": ["casual"]},
    {"id": 50, "image": "part1_image49.jpeg", "brand": "YOUNGLA", "category": "t-shirt", "color": "black", "style": ["casual", "athletic"]},
    {"id": 51, "image": "part2_image0.jpeg", "brand": "HUGO BOSS", "category": "hoodie", "color": "gray", "style": ["casual"]},
    {"id": 52, "image": "part2_image1.jpeg", "brand": "HUGO BOSS", "category": "jacket", "color": "navy", "style": ["smart-casual"]},
    {"id": 53, "image": "part2_image2.jpeg", "brand": "CLAIM DEFAME", "category": "jacket", "color": "black", "style": ["streetwear"]},
    {"id": 54, "image": "part2_image3.jpeg", "brand": "UNDER ARMOUR", "category": "jacket", "color": "white", "style": ["athletic"]},
    {"id": 55, "image": "part2_image4.jpeg", "brand": "UNDER ARMOUR", "category": "quarter-zip", "color": "gray", "style": ["athletic"]},
    {"id": 56, "image": "part2_image5.jpeg", "brand": "UNDER ARMOUR", "category": "quarter-zip", "color": "black", "style": ["athletic", "golf"]},
    {"id": 57, "image": "part2_image6.jpeg", "brand": null, "category": "hoodie", "color": "black", "style": ["athletic"]},
    {"id": 58, "image": "part2_image7.jpeg", "brand": "JOE'S", "category": "jeans", "color": "white", "style": ["casual"]},
    {"id": 59, "image": "part2_image8.jpeg", "brand": "KSUBI", "category": "jeans", "color": "black", "style": ["streetwear"]},
    {"id": 60, "image": "part2_image9.jpeg", "brand": "HUGO BOSS", "category": "shirt", "color": "white", "style": ["formal"]},
    {"id": 61, "image": "part2_image10.jpeg", "brand": "HUGO BOSS", "category": "long-sleeve-shirt", "color": "olive", "style": ["casual"]},
    {"id": 62, "image": "part2_image11.jpeg", "brand": "ZARA", "category": "t-shirt", "color": "black", "style": ["casual"]},
    {"id": 63, "image": "part2_image12.jpeg", "brand": "HUGO BOSS", "category": "jeans", "color": "navy", "style": ["casual"]},
    {"id": 64, "image": "part2_image13.jpeg", "brand": null, "category": "sweater", "color": "gray", "style": ["smart-casual"]},
    {"id": 65, "image": "part2_image14.jpeg", "brand": "BROOKS BROTHERS", "category": "sweater", "color": "coral", "style": ["smart-casual"]},
    {"id": 66, "image": "part2_image15.jpeg", "brand": null, "category": "cardigan", "color": "gray", "style": ["casual"]},
    {"id": 67, "image": "part2_image16.jpeg", "brand": "ALDO", "category": "loafers", "color": "black", "style": ["smart-casual"]},
    {"id": 68, "image": "part2_image17.jpeg", "brand": "AXEL ARIGATO", "category": "sneakers", "color": "white", "style": ["casual"]},
    {"id": 69, "image": "part2_image18.jpeg", "brand": "ALDO", "category": "sandals", "color": "brown", "style": ["casual"]},
    {"id": 70, "image": "part2_image19.jpeg", "brand": "ALDO", "category": "sneakers", "color": "white", "style": ["casual"]},
    {"id": 71, "image": "part2_image20.jpeg", "brand": "ALDO", "category": "sneakers", "color": "black", "style": ["smart-casual"]},
    {"id": 72, "image": "part2_image21.jpeg", "brand": "ALDO", "category": "sneakers", "color": "black", "style": ["smart-casual"]},
    {"id": 73, "image": "part2_image22.jpeg", "brand": "MR. B'S", "category": "oxford-shoes", "color": "black", "style": ["formal"]},
    {"id": 74, "image": "part2_image23.jpeg", "brand": "KENNETH COLE", "category": "boots", "color": "black", "style": ["smart-casual"]},
    {"id": 75, "image": "part2_image24.jpeg", "brand": "ALDO", "category": "sandals", "color": "black", "style": ["casual"]},
    {"id": 76, "image": "part2_image25.jpeg", "brand": "ORO", "category": "boots", "color": "black", "style": ["smart-casual"]},
    {"id": 77, "image": "part2_image26.jpeg", "brand": "ZARA", "category": "sweater", "color": "cream", "style": ["casual"]},
    {"id": 78, "image": "part2_image27.jpeg", "brand": "BROOKS BROTHERS", "category": "sweater", "color": "gray", "style": ["smart-casual"]},
    {"id": 79, "image": "part2_image28.jpeg", "brand": null, "category": "jeans", "color": "white", "style": ["casual", "streetwear"]},
    {"id": 80, "image": "part2_image29.jpeg", "brand": "ALLSAINTS", "category": "jeans", "color": "gray", "style": ["casual"]},
    {"id": 81, "image": "part2_image30.jpeg", "brand": "ZARA", "category": "jeans", "color": "blue", "style": ["streetwear"]},
    {"id": 82, "image": "part2_image31.jpeg", "brand": "ZARA", "category": "t-shirt", "color": "white", "style": ["casual"]},
    {"id": 83, "image": "part2_image32.jpeg", "brand": "UNDER ARMOUR", "category": "quarter-zip", "color": "white", "style": ["athletic"]},
    {"id": 84, "image": "part2_image33.jpeg", "brand": "ZARA", "category": "sweater", "color": "black", "style": ["casual"]},
    {"id": 85, "image": "part2_image34.jpeg", "brand": "ALLSAINTS", "category": "cardigan", "color": "black", "style": ["casual"]},
    {"id": 86, "image": "part2_image35.jpeg", "brand": "ZARA", "category": "cardigan", "color": "black", "style": ["casual"]},
    {"id": 87, "image": "part2_image36.jpeg", "brand": "UNDER ARMOUR", "category": "long-sleeve-shirt", "color": "white", "style": ["athletic"]},
    {"id": 88, "image": "part2_image37.jpeg", "brand": "BROOKS BROTHERS", "category": "sweater", "color": "black", "style": ["smart-casual"]},
    {"id": 89, "image": "part2_image38.jpeg", "brand": "HUGO BOSS", "category": "long-sleeve-shirt", "color": "black", "style": ["casual"]},
    {"id": 90, "image": "part2_image39.jpeg", "brand": "BOSS", "category": "shirt", "color": "white", "style": ["formal"]},
    {"id": 91, "image": "part2_image40.jpeg", "brand": "HUGO BOSS", "category": "shirt", "color": "black", "style": ["formal"]},
    {"id": 92, "image": "part2_image41.jpeg", "brand": "HUGO BOSS", "category": "cardigan", "color": "charcoal", "style": ["casual"]},
    {"id": 93, "image": "part2_image42.jpeg", "brand": "UNDER ARMOUR", "category": "joggers", "color": "gray", "style": ["athletic"]},
    {"id": 94, "image": "part2_image43.jpeg", "brand": "ZARA", "category": "sweatpants", "color": "cream", "style": ["casual", "athletic"]},
    {"id": 95, "image": "part2_image44.jpeg", "brand": "YOUNGLA", "category": "sweatpants", "color": "black", "style": ["athletic"]},
    {"id": 96, "image": "part2_image45.jpeg", "brand": "ROBERT BARAKETT", "category": "polo", "color": "black", "style": ["smart-casual"]},
    {"id": 97, "image": "manssion_necklace.jpg", "brand": "MANSSION", "category": "necklace", "color": "silver", "style": ["casual", "smart-casual"]},
    {"id": 98, "image": "manssion_bracelet.jpg", "brand": "MANSSION", "category": "bracelet", "color": "silver", "style": ["casual", "smart-casual"]}
  ]
}
;
